services:
  backend:
    build:
      context: ./server
      dockerfile: ./Dockerfile.dev
    ports:
      - "8000:8000"
    volumes:
      - ./server:/app
    environment:
      - BACKEND_ENV=dev
      - CRAWL4AI_API_URL=http://crawl4ai:11235
      - CRAWL4AI_API_TOKEN=wSTk2mirJ3dU7Psw2hY%mE@mNwWcWf19
      - OPENAI_API_KEY=
    depends_on:
      - crawl4ai
    restart: no

  frontend:
    build:
      context: ./client
      dockerfile: ./Dockerfile.dev
    ports:
      - "8080:8080"
    environment:
      - VITE_ENV=dev
      - VITE_API_URL=http://127.0.0.1:8000
    volumes:
      - ./client:/app
    depends_on:
      - backend
    restart: no

  crawl4ai:
    image: unclecode/crawl4ai:basic-amd64
    ports:
      - 11235:11235
    environment:
      - CRAWL4AI_API_TOKEN=wSTk2mirJ3dU7Psw2hY%mE@mNwWcWf19
    restart: no