services:
  backend:
    build:
      context: ./server
      dockerfile: ./Dockerfile.dev
    ports:
      - "8000:8000"
    volumes:
      - ./server:/app
    environment:
      - BACKEND_ENV=dev
    restart: no

  frontend:
    build:
      context: ./client
      dockerfile: ./Dockerfile.dev
    ports:
      - "8080:8080"
    environment:
      - VITE_ENV=dev
      - VITE_API_URL=http://127.0.0.1:8000
    volumes:
      - ./client:/app
    depends_on:
      - backend
    restart: no
